name: Deploy na VH.pl

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wgraj na serwer FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.vh16153.vh.net.pl
          username: vh16153
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: public_html/
          exclude: |
            **/.git*
            .git*
            aktualizuj.bat
